//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xoqal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xoqal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid currency..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_Currency {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid date..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_Date {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid date time..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_DateTime {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid duration..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_Duration {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid email address..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_EmailAddress {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid phone number..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_PhoneNumber {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid time..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_Time {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid URL..
        /// </summary>
        public static string DataAnnotations_DataType_ValidationError_Url {
            get {
                return ResourceManager.GetString("DataAnnotations_DataType_ValidationError_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be an integer..
        /// </summary>
        public static string DataAnnotations_IntegerAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DataAnnotations_IntegerAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}.TEST.
        /// </summary>
        public static string DataAnnotations_RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DataAnnotations_RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the regular expression &apos;{1}&apos;..
        /// </summary>
        public static string DataAnnotations_RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DataAnnotations_RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string DataAnnotations_RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DataAnnotations_RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string DataAnnotations_StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DataAnnotations_StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item(s) are selected. Are you sure to delete the selected items?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you select for delete is referenced by another item. You should first remove the refrencing item..
        /// </summary>
        public static string DeleteConflictErrorMessage {
            get {
                return ResourceManager.GetString("DeleteConflictErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item Category.
        /// </summary>
        public static string MenuItemCategory {
            get {
                return ResourceManager.GetString("MenuItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item Title.
        /// </summary>
        public static string MenuItemTitle {
            get {
                return ResourceManager.GetString("MenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of {0}.
        /// </summary>
        public static string OfPage {
            get {
                return ResourceManager.GetString("OfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
    }
}
